name: Terraform Apply
on: [push]


jobs:
  terraform_apply:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Install Terraform
      env:
            TERRAFORM_VERSION: "0.12.15"
      run: |
        terraform init
        terraform validate

  terraform-apply:
    runs-on: ubuntu-latest
    needs: terraform-init
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Apply Terraform
      run: |
        terraform apply -auto-approve
    - name: Show EC2 instance information
      run: |
        aws ec2 describe-instances --query 'Reservations[].Instances[].[PublicIpAddress,InstanceId,InstanceType]' --output table

  terraform-destroy:
    runs-on: ubuntu-latest
    needs: terraform-apply
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Destroy Terraform
      run: |
        terraform destroy -auto-approve

    - name: Terraform apply
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: terraform apply -auto-approve -input=false